#!/usr/bin/expect -f

set timeout 50

spawn "bluetoothctl"
expect "#"
send "power off\r"
expect "Changing power off succeeded"

send "power on\r"
expect "Changing power on succeeded"
send "discoverable on\r"
expect "Changing discoverable on succeeded"
send "pairable on\r"
expect "Changing pairable on succeeded"
send "agent on\r"
expect "Agent registered"
send "default-agent\r"
expect "Default agent request successful"

expect {
	timeout {puts "timed out"; exit}
	"Confirm passkey *" {send "yes\r"}
	"Authorize service *" {send "yes\r"}
}

expect "#"

sleep (1)

expect {
	timeout {puts "timed out"; exit}
	"Confirm passkey *" {send "yes\r"}
	"Authorize service *" {send "yes\r"}
}
     
expect "#"



