#!/usr/bin/expect -f

set timeout 40

spawn "bluetoothctl"
expect "#"
send "discoverable on\r"
expect "Changing discoverable on succeeded"
send "pairable on\r"
expect "Changing pairable on succeeded"
send "agent on\r"
expect "Agent registered"
send "default-agent\r"
expect "Default agent request successful"

expect {
		timeout{ 
				send "discoverable off\r"
				exit
		}

		"Confirm passkey *"	
}

send "yes\r"     
expect "Authorize service *"
send "yes\r"

send "discoverable off\r"
send "exit\r"
