#!/bin/bash

#sleep 5s

echo "*********************"
echo "* Project smart car *"
echo "*********************"

echo "**************"
echo "* 2017-01-12 *"
echo "**************"

echo "*************************"
echo "* Setting up PulseAudio *"
echo "*************************"

pulseaudio -D

echo "*******************************************"
echo "* Launching Bluetooth initialization code *"
echo "*******************************************"

/home/pi/bluetoothProject/./bluetooth-init

echo "*************************"
echo "* Launching main program*"
echo "*************************"

/home/pi/bluetoothProject/./main
