#!/usr/bin/expect -f

set timeout 20

spawn "bluetoothctl"
expect "#"
send "discoverable on\r"
expect "Changing discoverable on succeeded"
send "pairable on\r"
expect "Changing pairable on succeeded"
send "agent on\r"
expect "Agent registered"
send "default-agent\r"
expect "Default agent request successful"

expect "Confirm passkey *"
timeout { puts "\n\nScript Failure: \n\r"; exit}

send "yes\r"     
expect "Authorize service *"
send "yes\r"

;" Bluetooth connection done

send "exit\r"
